services:
  app:
    image: insider-sec-php:latest
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www/html
    environment:
      COMPOSER_CACHE_DIR: /tmp/composer-cache
      COMPOSER_ALLOW_SUPERUSER: "1"
    volumes:
      - ./:/var/www/html
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
    depends_on:
      - db
      - redis
    dns:
      - 8.8.8.8
      - 1.1.1.1

  web:
    image: nginx:1.27-alpine
    ports: ["8080:80"]
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: [app]
    dns:
      - 8.8.8.8
      - 1.1.1.1

  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: insider
      MYSQL_USER: insider
      MYSQL_PASSWORD: insider
      MYSQL_ROOT_PASSWORD: root
    ports: ["33066:3306"]
    dns:
      - 8.8.8.8
      - 1.1.1.1

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  vendor:
  node_modules:
